---
# Install NGINX as reverse proxy
  - name: Create user for NGINX
    user:
      name={{nginx_user}}
      password={{nginx_password}}
      state=present

  - name: Open proxy port for NGINX
    include: open_proxyport.yml
    when: platform == "centos_vm"

  - include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: NGINX
      rpm_filename: "{{ nginx_rpm }}"

  - name: Create proxy settings
    copy:
      src=nginx.conf
      dest=/etc/nginx
      owner={{nginx_user}}

  - name: Create custom proxy settings
    copy:
      src=v.hosts
      dest=/etc/nginx 

  - name: Starting the NGINX Service
    service:
      name=nginx
      state=started
      enabled=yes
    when: platform == "centos_vm"
