---
  # Open firewall proxy port
  - name: Starting the firewall Service
    service:
      name=firewalld
      state=started
      enabled=yes

  - name: Open proxy port
    command: 'firewall-cmd --permanent --add-port={{proxy_port | default(80)}}/tcp'

  - name: Reload firewall
    command: 'firewall-cmd --reload'