---
  - name: Installing the MongoDB YUM repository file
    copy:
      src={{mongo_repo}}
      dest=/etc/yum.repos.d/{{mongo_repo}}

  - name: Installing MongoDB
    yum:
      name=mongodb-org-server
      state=present

  - name: Changing MongoDB's IP binding setting to listen on all interfaces
    lineinfile:
      dest=/etc/mongod.conf
      regexp="bind_ip=127.0.0.1"
      line="# bind_ip=127.0.0.1"
      backrefs=yes

  - name: Starting the MongoDB service
    service:
      name=mongod
      state=started
      enabled=yes
