---
  - name: Install create repo
    yum:
      name: createrepo
      state: latest

  - name: Create local repository folder
    file:
      path: "{{ repository_folder }}"
      state: directory
      mode: 0777
      recurse: yes

  - name: Create local repository database
    command: "createrepo --database {{ repository_folder }}"
