---
  - name: Install create repo
    yum:
      name: createrepo
      state: latest

  - name: Create local repo folder
    file:
      path="/local_repo/"
      state=directory
      mode=0777

  - name: Copy rpm(s) to local repo
    copy:
      src="cache/{{item}}"
      dest="/local_repo/{{item}}"
    with_items:
      - "{{repository_list}}"

  - name: Create local repository database
    command: createrepo --database /local_repo
