---
  - name: Update OS
    yum:
      name: "*"
      state: latest

  - name: Install libexif
    include: plays/install_rpm.yml
    vars:
      rpm_app_name: "libexif"
      rpm_filename : "{{libexif_rpm}}"

  - name: Install Xvfb
    include: plays/install_rpm.yml
    vars:
      rpm_app_name: "xvfb"
      rpm_filename : "{{xvfb_rpm}}"

  - name: Copy Xvfb init script to host
    copy:
      src=xvfb
      dest=/etc/init.d/
      mode=0755

  - name: Start Xvfb after reboot
    command: "chkconfig xvfb on"

  - name: Start Xvfb process using display 99
    command: "/etc/init.d/xvfb start"

  - name: Install Chrome
    include: plays/install_rpm.yml
    vars:
      rpm_app_name: "Chrome Browser"
      rpm_filename : "{{chrome_rpm}}"

  - name: Install Firefox
    include: plays/install_rpm.yml
    vars:
      rpm_app_name: "Firefox"
      rpm_filename : "{{firefox_rpm}}"
