---
  - name: Create physical volume
    command: pvcreate /dev/sdb

  - name: Add physical volume to vg_root group
    command: vgextend vg_root /dev/sdb
    when: vg_name == "vg_root"

  - name: Create physical volume group {{ vg_name }}
    command: "vgcreate {{ vg_name }} /dev/sdb"
    when: vg_name != "vg_root"

  - name: Create {{ lv_size }} logical volume
    command: "lvcreate -n lv_registry -L {{ lv_size }} {{ vg_name }}"

  - name: Create an XFS file system
    command: "mkfs.xfs /dev/{{ vg_name }}/lv_registry"

  - name: Mount Docker registry
    command: "mount /dev/{{ vg_name }}/lv_registry /var/lib/registry"

  - name: Mount Docker registry on reboot
    lineinfile:
      dest: /etc/fstab
      backup: true
      line: "/dev/mapper/{{ vg_name }}-lv_registry /var/lib/registry                 xfs     defaults        0 0"
      state: present

  - name: Override Docker volume group
    lineinfile:
      dest: /usr/lib/docker-storage-setup/docker-storage-setup
      regexp: "# VG=(.*)"
      line: "VG={{ vg_name }}"
      state: present
    when: vg_name != "vg_root"

  - name: Set up storage for Docker
    command: docker-storage-setup
