Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.1"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 2048
    vbox.cpus = 2
    vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vbox.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.hostname = "cicompact"
  config.vm.define :cicompact do |cicompact| end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../plays/book-ci-compact.yml"
    ansible.inventory_path = "./inventory-remote.txt"
    ansible.sudo = true
    ansible.verbose = "vv"
    ansible.extra_vars = {
        ansible_ssh_user: 'vagrant',
        ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    }
  end
end