---
  - name: Clone PAMM seed repository
    git:
      repo=http://github.com/gatblau/pamm.seed
      dest=/home/{{gogs_user}}/gogs-repositories/pamm.seed
      update=yes

  - name: Change owner of PAMM seed repository
    file:
      path=/home/{{gogs_user}}/gogs-repositories/pamm.seed
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      recurse=yes
