---
  - name: Starting the firewall Service
    service:
      name=firewalld
      state=started
      enabled=yes

  - name: Open port for MySQL
    command: 'firewall-cmd --permanent --add-port={{ mysql_port | default(3306) }}/tcp'

  - name: Reload firewall
    command: 'firewall-cmd --reload'
