---
  - name: Create Jenkins plugins folder
    file:
      dest="{{jenkins_home}}/plugins"
      state=directory
      owner="{{jenkins_user}}"

  - name: Copying Jenkins plugins to the host
    copy:
      src="{{cache_folder}}/{{ item }}"
      dest="{{jenkins_home}}/plugins"
      owner=jenkins
      group=jenkins
    with_items:
      - "{{jenkins_plugins}}"
