---
  - name: Create jenkins group
    user:
      name="{{jenkins_group}}"
      state=present

  - name: Create jenkins user
    user:
      name="{{jenkins_user}}"
      password="{{jenkins_password}}"
      group="{{jenkins_group}}"
      state=present

  - name: Set jenkins user environment variables
    blockinfile:
      dest: "{{jenkins_user_home}}/.bashrc"
      insertafter: "# User specific aliases and functions"
      marker: "# {mark} Jenkins Environment Variables"
      block:  "export JAVA_HOME=/usr/java/default

export JENKINS_HOME={{jenkins_home}}

export PATH=$PATH:$JAVA_HOME/bin

"

  - name: Generate ssh keys for jenkins user
    include: generate_ssh_keys.yml
    when: blueprint != "silicon"

