---
  - include: ../../../install_rpm.yml
    vars:
      rpm_app_name: NGINX
      rpm_filename: "{{ nginx_rpm }}"

  - name: Create proxy settings
    copy:
      src=nginx.conf
      dest=/etc/nginx 

  - name: Create custom proxy settings
    copy:
      src=v.hosts
      dest=/etc/nginx 

  - name: Starting the NGINX Service
    service:
      name=nginx
      state=started
      enabled=yes
