---
  - include: ../../../install_rpm.yml
    vars:
      rpm_app_name: SONAR
      rpm_filename : "{{ sonar_rpm }}"

  - name: Copying SONAR configuration
    template: src=sonar.properties.j2
              dest=/opt/sonar/conf/sonar.properties

  - name: Creating the SONAR database
    mysql_db:
      name=sonar
      state=present

  - name: Starting the SONAR service
    service:
      name=sonar
      state=started
      enabled=yes
