---
# This play installs SonarQube - source code quality tool
#
# This role depends on the common, db_mysql and ci_proxy_nginx roles (see meta/main.yml)

  - name: Check Sonar installed
    stat: path=/opt/sonar
    register: sonar_exists

  - include: install_sonar.yml
    when: sonar_exists.stat.exists == false


