---
- name: Installing the Unzip command
  include: plays/install_rpm.yml
  vars:
    rpm_app_name: "Unzip command"
    rpm_filename : "{{ unzip_rpm }}"

- name: Installing the MariaDB server
  include: plays/install_rpm.yml
  vars:
    rpm_app_name: "MariaDB Server"
    rpm_filename : "{{ mariadb_server_rpm }}"

- name: Installing the MySQL Python Client
  include: plays/install_rpm.yml
  vars:
    rpm_app_name: "MySQL Python Client"
    rpm_filename : "{{ mysql_python_rpm }}"

- name: Starting the MariaDB Server
  service:
    name=mysql
    state=started
    enabled=yes

- name: Creating a read and write user to access the server remotely
  mysql_user:
    name={{ db_user }}
    host={{ item }}
    password={{ db_pwd }}
    priv=*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP
    state=present
  with_items:
    - localhost
    - %

- name: Updating MariaDB root password for all root accounts
  mysql_user:
    name=root host={{ item }}
    password={{ db_root_pwd }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: Deleting the Test Database
  mysql_db:
    name=test
    state=absent