---
  - name: Install Perl
    include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: PERL
      rpm_filename: "{{ perl_rpm }}"

  - name: Install Git Yum Repository
    include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: GIT yum repository
      rpm_filename: "{{ git_wandisco_rpm }}"

  - name: Install Git Perl
    include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: GIT_PERL
      rpm_filename: "{{ git_perl_rpm }}"

  - name: Install Git SCM
    include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: GIT_SCM
      rpm_filename: "{{ git_scm_rpm }}"
