---
- name: Configuring the compact Continuous Integration environment
  hosts: cicompact
  vars:
    environment: docker
  roles:
    - jenkins
    - artifactory
    - sonar
    - gogs
  sudo: no
  remote_user: root

