---
# The CI Deployment Server contains Artifactory 
  - name: Configuring the Continuous Integration Deployment Server environment
    hosts: cideploy
    roles:
      - ci_deployment
    sudo: yes
    remote_user: root

