---
  # Install Groovy
  - name: Check if Groovy installed
    stat: path=/usr/local/groovy
    register: groovy_exists

  - name: Install Groovy
    include: build_tools/install_groovy.yml
    when: groovy_exists.stat.exists == false

  # Install SBT
  - name: Check if SBT installed
    stat: path=/usr/local/sbt
    register: sbt_exists

  - name: Install SBT
    include: build_tools/install_sbt.yml
    when: sbt_exists.stat.exists == false

  # Install Gradle
  - name: Check if Gradle installed
    stat: path=/usr/local/gradle
    register: gradle_exists

  - name: Install Gradle
    include: build_tools/install_gradle.yml
    when: gradle_exists.stat.exists == false

  # Install Maven
  - name: Check if Maven installed
    stat: path=/usr/local/maven
    register: maven_exists

  - name: Install Maven
    include: build_tools/install_maven.yml
    when: maven_exists.stat.exists == false

  # Install Git
  - name: Check if Git installed
    stat: path=/bin/git
    register: git_exists

  - name: Install Git
    include: build_tools/install_git.yml
    when: git_exists.stat.exists == false

  # Install NodeJS
  - name: Installing NodeJS
    include: "plays/install_rpm.yml"
    vars:
      rpm_app_name: NodeJS
      rpm_filename: "{{nodejs_rpm}}"

  # Install Bower (npm)
  - name: Installing npm
    include: "plays/install_rpm.yml"
    vars:
      rpm_app_name: npm
      rpm_filename: "{{npm_rpm}}"

  - name: Installing Bower
    command: "npm install -g bower"

  # Install Sonar Runner
  - name: Check Sonar Runner installed
    stat: path=/usr/local/sonar_runner
    register: sonarrunner_exists
    changed_when: no

  - include: build_tools/install_sonar_runner.yml
    when: sonarrunner_exists.stat.exists == false