#
# Copyright (c) 2019 GATBLAU - www.gatblau.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Manages the execution of roles on a docker container.
# The only part of this playbook that needs changing is the list of roles as described below.
# The name of the playbook should be updated to reflect the host name - e.g. database.yml
#
#
# The playbook to deploy SonarQube
#
---
- name: Initialise Managed Hosts
  hosts: local
  connection: local
  become: no
  roles:
    - up_host

- name: Install baseline requirements
  hosts: citools
  connection: "{{ connection }}"
  become: "{{ become }}"
  roles:
    - baseline

- name: Provisioning database server
  hosts: database
  connection: "{{ connection }}"
  become: "{{ become }}"
  roles:
    - { role: mariadb_install,         when: install_mode != "offline" }
    - { role: mariadb_install_offline, when: install_mode == "offline" }
    - mariadb

- name: Provisioning quality server
  hosts: quality
  connection: "{{ connection }}"
  become: "{{ become }}"
  roles:
    - sonar_install
    - sonar
...