---
# This play installs Java alternatives
    - name: Installing Java Alternative
      command: "alternatives --install /usr/bin/java java /usr/java/default/bin/java 1"

    - name: Configuring Java Alternative
      command: "alternatives --set java /usr/java/default/bin/java"
