---
  - name: Create group for Jenkins user
    group:
      name="{{jenkins_group}}"
      state=present

  - name: Create user for Jenkins
    user:
      name="{{jenkins_user}}"
      password="{{jenkins_password}}"
      group="{{jenkins_group}}"
      state=present
