---
  - name: Create jenkins user
    include_tasks: jenkins_user.yml

  - name: Create builder
    include_tasks: install_build_tools.yml

  - name: Install PAMM seed dependencies
    include_tasks: install_pamm_dependencies.yml

  - name: Install swarm client
    copy:
      src="cache/{{swarm_client}}"
      dest=/opt/swarm-client-jar-with-dependencies.jar
      mode=0666

  - name: Copy entrypoint script for Jenkins PAMM builder container
    copy:
      src=entrypoint.sh
      dest=/entrypoint.sh
      mode=0755
