---
  - include: "{{plays_folder}}/install_tool.yml"
    vars:
      tool_name : Activator
      folder_name : activator-dist-1.3.5
      zip_filename: typesafe-activator-1.3.5.zip
      zip_has_folder : true
      add_version_to_folder : false
      has_bin_folder : false

  - name: Making activator executable
    file: path=/usr/local/activator/default/activator mode=a+x