---
# This play installs Artifactory - binary repository and deployment tool
#
# See meta/main.yml for role dependencies
  - name: Create user for Artifactory
    user:
      name={{artifactory_user}}
      password={{artifactory_password}}
      state=present

  - include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: Artifactory
      rpm_filename: "{{artifactory_rpm}}"

  - name: Copying Artifactory configuration
    template: 
      src=artifactory.mysql.properties.j2 
      dest=/var/opt/jfrog/artifactory/etc/storage.properties
      owner={{artifactory_user}}

  - name: Set Artifactory start script to executable
    file:
      path=/var/opt/jfrog/artifactory/misc/service/artifactory
      mode=0770
    when: platform == "docker"

  - name: Copying the Artifactory database script to the host
    copy: 
      src=artifactory.createdb.sql 
      dest=/tmp/artifactory.createdb.sql

  - name: Creating the Artifactory database
    mysql_db: 
      state=import name=mysql 
      target=/tmp/artifactory.createdb.sql

  - name: Deploying the MySQL connector to the Artifactory web server
    copy:
      src="{{cache_folder}}/{{ mysql_connector }}"
      dest=/var/opt/jfrog/artifactory/tomcat/lib/{{ mysql_connector }}
      owner={{artifactory_user}}
      mode=0775

  - name: Removing the Artifactory database script from the host
    file: 
      path=/tmp/artifactory.createdb.sql state=absent

  - name: Starting the Artifactory Service
    service: 
      name=artifactory 
      state=started 
      enabled=yes
    when: platform == "centos_vm"

