---
  - name: Create Jenkins plugins folder
    file:
      dest="{{jenkins_home}}/plugins"
      state=directory
      owner="{{jenkins_user}}"

  - name: Download plugins
    get_url:
      url=http://updates.jenkins-ci.org/latest/{{item}}
      dest="{{jenkins_home}}/plugins"
    with_items:
      - "{{jenkins_plugins}}"

  # Need to use command as file module does not allow recursive setting of permissions
  - name: Set plugins owner
    command: chown -R {{jenkins_user}}:{{jenkins_user}} "{{jenkins_home}}/plugins"
