---
- name: Create Jenkins home folder
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group}}"
    mode: 0700

- name: Set slave variables
  set_fact:
    slave_host: "{{ ansible_hostname }}"
    node_host:  "{{ ansible_default_ipv4.address }}"

- name: Create folder for node config file
  file:
    path: "/var/lib/jenkins/nodes/{{ slave_host }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0700
    state: directory
  delegate_to: "{{ item }}"
  with_items: "{{ groups['build'] | first }}"

- name: Create {{ ansible_hostname }} node config file
  template:
    src:  "node.j2"
    dest: "/var/lib/jenkins/nodes/{{ slave_host }}/config.xml"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['build'] | first }}"

- name: Restart Jenkins Master
  service:
    name: jenkins
    state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{ groups['build'] | first }}"
