---
  - include: ../../../install_rpm.yml
    vars:
      rpm_app_name: Jenkins
      rpm_filename: "{{ jenkins_rpm }}"

  - name: Copying Jenkins plugins to the host
    copy:
      src={{ item }}
      dest=/var/lib/jenkins/plugins/ 
      owner=jenkins 
      group=jenkins
    with_fileglob:
      - ../../../files/cache/*.hpi

  - name: Create Jenkins users
    copy:
      src=users 
      dest=/var/lib/jenkins 
      owner=jenkins 
      group=jenkins

  - name: Set up Jenkins configuration
    copy:
      src={{ item }} 
      dest=/var/lib/jenkins 
      owner=jenkins 
      group=jenkins
    with_fileglob:
      - config/*.xml

  - name: Set up Jenkins to Sonar configuration
    template: src=hudson.plugins.sonar.SonarPublisher.xml.j2
              dest=/var/lib/jenkins/hudson.plugins.sonar.SonarPublisher.xml

#  - name: Create Jenkins build jobs
#    copy:
#      src=jobs 
#      dest=/var/lib/jenkins 
#      owner=jenkins 
#      group=jenkins

  - name: Copying Jenkins build jobs to the host
    copy: 
      src=jobs.zip
      dest=/tmp

  - name: Unzipping Jenkins build jobs
    unarchive:
      src=/tmp/jobs.zip
      dest=/var/lib/jenkins
      copy=no
      owner=jenkins

  - name: Removing Jenkins jobs from the host
    file: path=/tmp/jobs.zip state=absent

  - name: Create Jenkins proxy
    copy:
      src=proxy/jenkins
      dest=/etc/sysconfig
      owner=root
      mode=600

  - name: Starting the Jenkins Service
    service:
      name=jenkins 
      state=started 
      enabled=yes
